name = "AlmostBlockDiagonals"
uuid = "a95523ee-d6da-40b5-98cc-27bc505739d5"
authors = ["Qingyu Qu"]
version = "0.1.1"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"

[compat]
ConcreteStructs = "0.2"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
